"""
Medical RAG Prompts Module
===========================

World-class prompts for Clinical Decision Support System.
"""

from .system_prompts import (
    MEDICAL_DIAGNOSTIC_SYSTEM_PROMPT,
    QUERY_EXPANSION_PROMPT,
    DIAGNOSTIC_REASONING_PROMPT,
    DRUG_INTERACTION_PROMPT,
    EVIDENCE_SYNTHESIS_PROMPT,
)
from .safety_prompts import (
    SAFETY_GUARDRAILS_PROMPT,
    ESCALATION_TRIGGERS,
    RESPONSE_BLOCKERS,
)

__all__ = [
    "MEDICAL_DIAGNOSTIC_SYSTEM_PROMPT",
    "QUERY_EXPANSION_PROMPT",
    "DIAGNOSTIC_REASONING_PROMPT",
    "DRUG_INTERACTION_PROMPT",
    "EVIDENCE_SYNTHESIS_PROMPT",
    "SAFETY_GUARDRAILS_PROMPT",
    "ESCALATION_TRIGGERS",
    "RESPONSE_BLOCKERS",
]
